// Generated by CoffeeScript 1.8.0
'use strict';
var Constants;

Constants = (function() {
  function Constants() {
    this.BASE_PATH = process.cwd();
    this.PORT = 1337;
    this.HOST = '127.0.0.1';
    this.ERRORS = ['EADDRINUSE', 'ECONNRESET', 'EADDRINUSE', 'EADDRINUSE'];
    this.VERSION = "1.0.0.2";
  }

  return Constants;

})();

global.constants = new Constants;
