// Generated by CoffeeScript 1.8.0
'use strict';
var DependencyResolver, path;

path = require('path');

DependencyResolver = (function() {
  function DependencyResolver(logger) {
    this.logger = logger;
    this.logger.help("The dependency resolver was initialized...\nUse this tool for include general and custom dependencies\nThanks and good coding!!!\nStarting to resolve dependencies...\n-----------------------------------");
  }

  DependencyResolver.prototype.load = function(dependencyName, dependencyPath) {
    var dependency, e;
    this.logger.data("loading " + dependencyName + "...");
    try {
      if (dependencyPath.indexOf('\\') > -1 || dependencyPath.indexOf('/') > -1) {
        dependencyPath = path.join("" + (process.cwd()), "" + dependencyPath);
      }
      dependency = require(dependencyPath);
      this.logger.info("* " + dependencyName + " loaded ...");
    } catch (_error) {
      e = _error;
      this.logger.error("critical error loading " + dependencyName + " \r\n error: " + e + "\r\n*********************************", e);
    }
    return dependency;
  };

  return DependencyResolver;

})();

module.exports = DependencyResolver;
