// Generated by CoffeeScript 1.8.0
'use strict';
var Logger;

Logger = (function() {
  function Logger(outputMethod) {
    this.output = outputMethod || console.log;
  }

  Logger.prototype.message = function(message) {
    return this.output(message);
  };

  Logger.prototype.error = function(message, exception) {
    return this.output(message);
  };

  Logger.prototype.warning = function(message) {};

  return Logger;

})();

module.exports = Logger;
