// Generated by CoffeeScript 1.8.0
'use strict';
var Logger, colors;

colors = require('colors');

Logger = (function() {
  function Logger(outputMethod) {
    colors.setTheme({
      silly: 'rainbow',
      input: 'grey',
      verbose: 'cyan',
      prompt: 'grey',
      info: 'green',
      data: 'grey',
      help: 'cyan',
      warn: 'yellow',
      debug: 'blue',
      error: 'red'
    });
    this.output = outputMethod || console.log;
  }

  Logger.prototype.info = function(message) {
    return this.output(message.info);
  };

  Logger.prototype.error = function(message, exception) {
    return this.output(message.error);
  };

  Logger.prototype.warning = function(message) {
    return this.output(message.warn);
  };

  Logger.prototype.help = function(message) {
    return this.output(message.help);
  };

  Logger.prototype.data = function(message) {
    return this.output(message.data);
  };

  return Logger;

})();

module.exports = Logger;
