// Generated by CoffeeScript 1.9.0
'use strict';
var DependencyResolver, GameProtocol, Logger, Mongo, net;

Mongo = require('./Model/MongoConnector');

DependencyResolver = require('./System/DependencyResolver');

Logger = require('./System/Logger');

global.resolver = new DependencyResolver(global.log = new Logger);

net = global.resolver.load('net', 'net');

GameProtocol = global.resolver.load('GameProtocol', 'Communication/GameProtocol');

global.resolver.load('Constants', 'System/Constants');

(function() {
  var mng, server;
  server = net.createServer(function(socket) {
    var protocol;
    global.log.info('new client connected');
    return protocol = new GameProtocol(server, socket);
  });
  global.log.info("\r\nserver version " + global.constants.VERSION + " listening on port: " + global.constants.PORT + "\r\n");
  server.listen(global.constants.PORT, global.constants.HOST);
  return mng = new Mongo;
})();
