// Generated by CoffeeScript 1.8.0
'use strict';
var CheatAnalyzerProtocol;

CheatAnalyzerProtocol = (function() {
  function CheatAnalyzerProtocol(server, socket) {
    this.server = server;
    this.socket = socket;
  }

  return CheatAnalyzerProtocol;

})();

module.exports = CheatAnalyzerProtocol;
