// Generated by CoffeeScript 1.8.0
'use strict';
var CommunicationProtocol;

CommunicationProtocol = (function() {
  function CommunicationProtocol(server, socket) {
    this.server = server;
    this.socket = socket;
  }

  return CommunicationProtocol;

})();
