// Generated by CoffeeScript 1.8.0
'use strict';
var GameProtocol, SecurityProtocol,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

SecurityProtocol = global.resolver.load('SecurityProtocol', 'Communication/SecurityProtocol');

GameProtocol = (function() {
  function GameProtocol(server, socket) {
    this.server = server;
    this.socket = socket;
    this.criptoAnalyzer = new SecurityProtocol(this.server, this.socket);
    this.socket.on('error', (function(_this) {
      return function(e) {
        var _ref;
        if (_ref = e.code, __indexOf.call(global.constants.ERRORS, _ref) >= 0) {
          return global.log.error("error handled: " + e);
        }
      };
    })(this));
    this.server.on('error', (function(_this) {
      return function(e) {
        var _ref;
        if (_ref = e.code, __indexOf.call(global.constants.ERRORS, _ref) >= 0) {
          return global.log.error("error handled: " + e);
        }
      };
    })(this));
    this.socket.on('data', (function(_this) {
      return function(chunk) {
        var decryptedData, e, encryptedChunk, reply;
        encryptedChunk = '';
        try {
          if (chunk.length > 300) {
            chunk = (chunk.toString('utf-8')).trim();
            global.log.data("received " + chunk + "\n*********************************");
            decryptedData = _this.criptoAnalyzer.decrypt(chunk);
            global.log.info("replying: " + decryptedData);
            reply = _this.criptoAnalyzer.encrypt("i've received " + decryptedData);
            return _this.socket.write(reply);
          } else {
            return _this.criptoAnalyzer.test(chunk);
          }
        } catch (_error) {
          e = _error;
          return global.log.error(e.toString(), e);
        }
      };
    })(this));
    this.socket.on('end', function() {
      global.log.warning("client signed out");
      return socket.end();
    });
  }

  return GameProtocol;

})();

module.exports = GameProtocol;
