// Generated by CoffeeScript 1.8.0
var MongoConnector, Mongoose;

Mongoose = require('Mongoose');

MongoConnector = (function() {
  function MongoConnector() {
    var db;
    db = Mongoose.connection;
    db.on('error', console.error);
    db.once('open', function() {
      return console.log('Conectado ao MongoDB.');
    });
    Mongoose.connect('mongodb://127.0.0.1/test');
  }

  return MongoConnector;

})();

module.exports = MongoConnector;
