// Generated by CoffeeScript 1.8.0
var Player;

Player = (function() {
  function Player() {
    this.login = null;
    this.password = null;
    this.name = null;
    this.age = 0;
    this.email = null;
    this.chars = null;
    this.photo = null;
  }

  return Player;

})();

module.exports = User;
