// Generated by CoffeeScript 1.8.0
var http;

http = require('http');

http.createServer(function(req, res) {
  res.writeHead(200, {
    'content-type': 'text/plain'
  });
  res.end('hello, world\n');
}).listen(1337, '127.0.0.1');

console.log("server running");
