// Generated by CoffeeScript 1.8.0
require(["video-loader"], function(videoLoader) {
  var loader;
  loader = new VideoLoader(["assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4", "assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4", "assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4"], true);
  loader.onProgress(function(arg) {
    return console.log(arg);
  });
  loader.onFinish(function(arg) {
    return console.log(arg);
  });
  return loader.start(function() {
    return console.log("Processo de carregamento finalizado!!");
  });
});
