// Generated by CoffeeScript 1.8.0
require(["video-loader"], function(videoLoader) {
  var loader;
  loader = new VideoLoader(["assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4", "assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4", "assets/video/Dope D.O.D. Ft. Onyx - Panic Room (Official Video).mp4"], false);
  loader.onProgress(function(arg) {
    return console.log(arg);
  });
  loader.onFinish(function(arg) {
    var videoElement;
    console.log(arg);
    videoElement = document.createElement("video");
    videoElement.width = 640;
    videoElement.height = 480;
    videoElement.src = arg.cacheUrl;
    document.body.appendChild(videoElement);
    return videoElement.play();
  });
  return loader.start(function() {
    return console.log("Processo de carregamento finalizado!!");
  });
});
