// Generated by CoffeeScript 1.8.0
var CoffeeTask, coffee, path, watch;

coffee = require('gulp-coffee');

watch = require('gulp-watch');

path = require('path');

CoffeeTask = (function() {
  function CoffeeTask(gulp, config, basePath, buildPath) {
    this.gulp = gulp;
    this.config = config;
    this.basePath = basePath != null ? basePath : "/app";
    this.buildPath = buildPath != null ? buildPath : "/build";
    if (this.config === null) {
      this.config = {
        from: "" + basePath + "/scripts/coffee/*.coffee",
        to: "" + buildPath + "/scripts/js/"
      };
    }
  }

  CoffeeTask.prototype.setupTask = function() {
    return this.gulp.src(this.config.from).pipe(watch(this.config.from)).pipe(coffee()).pipe(this.gulp.dest(this.config.to));
  };

  return CoffeeTask;

})();

if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
  module.exports = CoffeeTask;
}
