// Generated by CoffeeScript 1.8.0
var LessTask, less, path, watch;

less = require('gulp-less');

watch = require('gulp-watch');

path = require('path');

LessTask = (function() {
  function LessTask(gulp, config, basePath, buildPath) {
    this.gulp = gulp;
    this.config = config;
    this.basePath = basePath != null ? basePath : "/app";
    this.buildPath = buildPath != null ? buildPath : "/build";
    if (this.config === null) {
      this.config = {
        from: "" + basePath + "/style/less/*.less",
        to: "" + buildPath + "/style/css/"
      };
    }
    console.log(this.config);
  }

  LessTask.prototype.setupTask = function() {
    return this.gulp.src(this.config.from).pipe(watch(this.config.from)).pipe(less()).pipe(this.gulp.dest(this.config.to));
  };

  return LessTask;

})();

if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
  module.exports = LessTask;
}
