// Generated by CoffeeScript 1.8.0
var Gulpfile, allTasks, browserSync, gulp, gulpfile;

browserSync = require('browser-sync');

gulp = require('gulp');

allTasks = require('./gulp-tasks');

Gulpfile = (function() {
  function Gulpfile() {
    this.serverPath = '/';
    this.environment = 'dev';
    this.startTasks = [];
  }

  Gulpfile.prototype.addTask = function(task, env) {
    return gulp.task(task, function() {
      var taskDependency, taskObject;
      taskDependency = require(env.inject);
      taskObject = new taskDependency(gulp, env.config);
      return taskObject.setupTask();
    });
  };

  Gulpfile.prototype.start = function() {
    var allEnvironments, task;
    if (allTasks != null) {
      for (task in allTasks) {
        if (task != null) {
          allEnvironments = allTasks[task];
          if ((allEnvironments != null) && (allEnvironments[this.environment] != null) && (allEnvironments[this.environment].inject != null)) {
            this.startTasks.push(task);
            this.addTask(task, allEnvironments[this.environment]);
          }
        }
      }
    }
    return gulp.task('default', this.startTasks);
  };

  return Gulpfile;

})();

gulpfile = new Gulpfile;

gulpfile.start();
